### ISSUE TITLE
Assignment 3 To-Do List 

### ISSUE THREAD

**Issue by Osvak** [Osvak/TurboTribble#1]
# Assignment 3 To-Do List

## Website
- [x] Short introduction to the engine and it's context (university subject).
- [x] Team or members photo and quick explanation of the individual work of each member.
- [x] Short Explanation of the main core sub-systems.
- [ ] Detailed explanation of last assingment sub-system, containing two animated gif that shows editor and in-game functionality
- [ ] One minute video speed-up that shows the process of authoring scenes in your editor, especially with your core technology from the last assingment.
- [x] Link to the code repository and last release to download.
- [x] License.

## Assingment content
- [x] Engine default window 1024x 768 centered on the screen and should be resizable.
- [x] The build loads directly the scene with the required demo specifications.
- [ ] Sub-systems work correctly with time controls (Play/Pause/Stop) and should be properly serialized into a scene. 

## User interface
- [ ] Main menu with fullscreen background image.
- [ ] Imput box to request the name.
- [ ] Button to start (can be pressed with mouse or keyboard). When pressed it fades away and shows the Town scene.
- [ ] Pressing F1 open options (draggable) window with, at least, a checkbox to activate/deactivate vsync.
- [ ] For the hud just add crosshair in the miffle of the screen.
